# Generated by Django 3.2.9 on 2022-01-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Seat',
        ),
        migrations.RenameModel(
            old_name='PlaceTicket',
            new_name='SeatTicket',
        ),
        migrations.RenameModel(
            old_name='PlaceTicketType',
            new_name='SeatTicketType',
        ),
    ]
