# Generated by Django 3.2.9 on 2022-01-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220104_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatticket',
            name='bilet',
        ),
        migrations.RemoveField(
            model_name='seatticket',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='seattickettype',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='seattickettype',
            name='tip_bilet',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='SeatTicket',
        ),
        migrations.DeleteModel(
            name='SeatTicketType',
        ),
    ]
