# Generated by Django 3.2.9 on 2022-01-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220104_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='pret_final',
        ),
        migrations.DeleteModel(
            name='EventVoucher',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
